version: '3.5'
services:
  proposal-app:
    image: proposal-app
    environment:
      DB_URL: jdbc:postgresql://db:5432/propostadb
      DB_USER: postgres
      DB_PASSWORD: admin
      spring.profiles.active: prod
    depends_on:
      rabbit-mq:
        condition: service_healthy
    ports:
      - "8080:8080"
  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping # It'll try to achieve the condition service_healthy in 3 tries
      timeout: 5s
      interval: 5s
      retries: 3
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: propostadb